# Generated by Django 3.1.2 on 2020-10-25 15:19

from django.db import migrations, models
import importcsv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KW',
            fields=[
                ('_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=50)),
                ('PID', models.IntegerField(default=0, validators=[importcsv.models.pid_validation])),
            ],
        ),
    ]
