# Generated by Django 3.1.2 on 2020-10-26 11:15

import django.core.validators
from django.db import migrations, models
import importcsv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KW',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=50)),
                ('PID', models.IntegerField(default=0, validators=[importcsv.models.pid_validation])),
                ('convert_rate', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('difficulty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('search_volume', models.IntegerField()),
                ('landing_title', models.CharField(max_length=100)),
                ('landing_slug', models.CharField(max_length=50)),
                ('hint', models.TextField()),
                ('external_anchor_text', models.CharField(max_length=50)),
                ('external_link', models.URLField()),
                ('internal_link', models.URLField()),
                ('back_link', models.URLField()),
                ('landing_type', models.CharField(choices=[('\u200cBP', 'مقاله\u200cی وبلاگ'), ('BT', 'برچسب وبلاگ'), ('BC', 'دسته\u200cبندی وبلاگ'), ('Pa', 'برگه'), ('Pr', 'محصول'), ('PC', 'دسته\u200cبندی محصول'), ('PT', 'برچسب محصول'), ('PA', 'ویژگی محصول')], default='\u200cBP', max_length=3)),
                ('landing_status', models.CharField(choices=[('Av', 'موجود'), ('Re', 'منتشر شد'), ('Wr', 'درحال نوشتن'), ('Ua', 'ناموجود')], default='Ua', max_length=3)),
            ],
        ),
    ]
